### ISSUE TITLE
ValueError in icmpv6.py after pinging nonexistent IPv6 address

### ISSUE THREAD

**Issue by ChristosKon** [noxrepo/pox#157]
Hello,

I use mininext over mininet 2.1.0p1, openflow 1.0, pox dart branch and nicira extension. My topology:

```
h1 --- s1 --- r1 --- s2 --- h2
```

s1: Open vSwitch
r1: quagga router

When I `ping6` a nonexistent IPv6 address within the same network everything is fine. When I `ping6` a nonexistent IPv6 address to another network then I have the following error:

```
ERROR:core:Exception while handling OpenFlowNexus!PacketIn...
Traceback (most recent call last):
  File "/home/mininet/pox/pox/lib/revent/revent.py", line 241, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/mininet/pox/pox/lib/revent/revent.py", line 291, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/mininet/pox/pox/lib/revent/revent.py", line 166, in _invoke
    return handler(self, *args, **kw)
  File "/home/mininet/pyretic/of_client/pox_client.py", line 764, in _handle_PacketIn
    packet = event.parsed
  File "/home/mininet/pox/pox/openflow/__init__.py", line 193, in parsed
    return self.parse()
  File "/home/mininet/pox/pox/openflow/__init__.py", line 185, in parse
    self._parsed = ethernet(self.data)
  File "/home/mininet/pox/pox/lib/packet/ethernet.py", line 106, in __init__
    self.parse(raw)
  File "/home/mininet/pox/pox/lib/packet/ethernet.py", line 127, in parse
    self.next = ethernet.parse_next(self, self.type, raw, ethernet.MIN_LEN)
  File "/home/mininet/pox/pox/lib/packet/ethernet.py", line 134, in parse_next
    return parser(raw[offset:], prev)
  File "/home/mininet/pox/pox/lib/packet/ipv6.py", line 297, in __init__
    self.parse(raw)
  File "/home/mininet/pox/pox/lib/packet/ipv6.py", line 378, in parse
    self.next = icmpv6(raw=raw[offset:offset+length], prev=self)
  File "/home/mininet/pox/pox/lib/packet/icmpv6.py", line 941, in __init__
    self.parse(raw)
  File "/home/mininet/pox/pox/lib/packet/icmpv6.py", line 1006, in parse
    buf_len=buf_len,prev=self)
  File "/home/mininet/pox/pox/lib/packet/icmpv6.py", line 810, in unpack_new
    o = cls(raw=raw,prev=prev)
  File "/home/mininet/pox/pox/lib/packet/icmpv6.py", line 891, in __init__
    self.parse(raw)
  File "/home/mininet/pox/pox/lib/packet/icmpv6.py", line 909, in parse
    (self.unused, _) = struct.unpack('!I', raw[:self.MIN_LEN])
ValueError: need more than 1 value to unpack
```

The result of:

`print struct.unpack('!I', raw[:self.MIN_LEN])`  is `(0,)`

I am not an expert but I think that the source of the problem is that pinging a non existent IPv6 address within the same network produces a `Destination unreachable: Address unreachable` reply while pinging a non existent IPv6 address in another network doesn't produce any answer and we don't handle this length.

`ping6` to a nonexistent IPv6 address means that sender sends 3 unanswered Neighbour Solicitation messages. This error appears at the expiration time of waiting an answer to the last Neighbour Solicitation.

Let me know if you need some more information.

**Comment by MurphyMc** [comment]
Looks like like 909 of icmpv6.py should be:

```
(self.unused,) = struct.unpack('!I', raw[:self.MIN_LEN])
```

**Comment by ChristosKon** [comment]
Yes, it works fine with your proposal.

**Comment by MurphyMc** [comment]
Thanks for the bug report.  Fixed in eel.
