### ISSUE TITLE
Link down event causes topology to crash

### ISSUE THREAD

**Issue by ghost** [noxrepo/pox#17]
Start POX with topology and discovery:

``` bash
$ ./pox.py openflow topology openflow.topology openflow.discovery
```

Start Mininet:

``` bash
$ sudo mn --controller=remote --topo=tree,depth=2,fanout=2 --ip=[...] --port=6633
```

Wait for all links to be detected and run:

```
mininet> s5 ifconfig s5-eth2 down
```

Wait a while and this happens:

```
INFO:openflow.discovery:link timeout: 00-00-00-00-00-05.2 -> 00-00-00-00-00-07.3
INFO:openflow.discovery:link timeout: 00-00-00-00-00-07.3 -> 00-00-00-00-00-05.2
Task <Timer/tid1> caused exception and was de-scheduled
Traceback (most recent call last):
  File "/home/user/pox/pox/lib/recoco/recoco.py", line 276, in cycle
    rv = t.execute()
  File "/home/user/pox/pox/lib/recoco/recoco.py", line 94, in execute
    return self.gen.send(v)
  File "/home/user/pox/pox/lib/recoco/recoco.py", line 751, in run
    rv = self._callback(*self._args,**self._kw)
  File "/home/user/pox/pox/openflow/discovery.py", line 262, in _expireLinks
    self._deleteLinks(deleteme)
  File "/home/user/pox/pox/openflow/discovery.py", line 387, in _deleteLinks
    self.raiseEvent(LinkEvent, False, link)
  File "/home/user/pox/pox/lib/revent/revent.py", line 280, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/user/pox/pox/lib/revent/revent.py", line 158, in _invoke
    return handler(self, *args, **kw)
  File "/home/user/pox/pox/openflow/topology.py", line 85, in _handle_openflow_discovery_LinkEvent
    sw1.ports[link.port1].entities.remove(sw2)
KeyError: <OpenFlowSwitch 00-00-00-00-00-05>
```

I believe this is happening because the link timeout event is symmetric, and the link is already removed when it happens the second time, causing the exception. A simple check would probably solve this problem:

**In pox/openflow/topology.py:**
Line 85 to 88 could be:

``` python
  if sw2 in sw1.ports[link.port1].entities:
    sw1.ports[link.port1].entities.remove(sw2)
  if sw1 in sw2.ports[link.port2].entities:
    sw2.ports[link.port2].entities.remove(sw1)
```

**Comment by MurphyMc** [comment]
Thanks for the report.  This should be addressed in beaf1b4aaff:

Fix exception on link down

This closes issue #17.

Topology is getting a huge makeover and this will no longer be relevant, but might as well address this bug in the meantime.
