### ISSUE TITLE
ofp_action_output does not accept OFPP_NONE

### ISSUE THREAD

**Issue by icehawk1** [noxrepo/pox#171]
I am trying to run [this script](https://github.com/nampho2/CS6250/blob/master/assignment-7/pox_firewall.py)

I am using the latest pox source code from github. I also tried checking out the betta branch as recommended by the openflow tutorial I am doing. Its the same.

However, the line 59 is triggering an error:
msg.actions.append(of.ofp_action_output(port=of.OFPP_NONE))

This is the output I am seeing from pox:

martin:/tmp/pox-carp$ ./pox.py  misc.pox_firewall
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
INFO:core:POX 0.2.0 (carp) is up.
INFO:openflow.of_01:[00-00-00-00-00-01 1] connected
INFO:misc.pox_firewall:OFPP_NONE: 65535
INFO:misc.pox_firewall:Installing firewall rule for src=00:00:00:00:00:01, dst=00:00:00:00:00:02
INFO:misc.pox_firewall:Hubifying 00-00-00-00-00-01
ERROR:openflow.of_01:[00-00-00-00-00-01 1] OpenFlow Error:
[00-00-00-00-00-01 1] Error: header: 
[00-00-00-00-00-01 1] Error:   version: 1
[00-00-00-00-00-01 1] Error:   type:    1 (OFPT_ERROR)
[00-00-00-00-00-01 1] Error:   length:  76
[00-00-00-00-00-01 1] Error:   xid:     6
[00-00-00-00-00-01 1] Error: type: OFPET_BAD_ACTION (2)
[00-00-00-00-00-01 1] Error: code: OFPBAC_BAD_OUT_PORT (4)
[00-00-00-00-00-01 1] Error: datalen: 64
[00-00-00-00-00-01 1] Error: 0000: 01 0e 00 50 00 00 00 06  00 10 00 13 00 00 00 00   |...P............|
[00-00-00-00-00-01 1] Error: 0010: 00 00 00 01 00 00 00 00  00 02 00 00 00 00 00 00   |................|
[00-00-00-00-00-01 1] Error: 0020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
[00-00-00-00-00-01 1] Error: 0030: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 14   |................|
ERROR:openflow.of_01:[00-00-00-00-00-01 1] OpenFlow Error:
[00-00-00-00-00-01 1] Error: header: 
[00-00-00-00-00-01 1] Error:   version: 1
[00-00-00-00-00-01 1] Error:   type:    1 (OFPT_ERROR)
[00-00-00-00-00-01 1] Error:   length:  76
[00-00-00-00-00-01 1] Error:   xid:     6
[00-00-00-00-00-01 1] Error: type: OFPET_BAD_ACTION (2)
[00-00-00-00-00-01 1] Error: code: OFPBAC_BAD_OUT_PORT (4)
[00-00-00-00-00-01 1] Error: datalen: 64
[00-00-00-00-00-01 1] Error: 0000: 01 0e 00 50 00 00 00 06  00 10 00 13 00 00 00 00   |...P............|
[00-00-00-00-00-01 1] Error: 0010: 00 00 00 02 00 00 00 00  00 01 00 00 00 00 00 00   |................|
[00-00-00-00-00-01 1] Error: 0020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
[00-00-00-00-00-01 1] Error: 0030: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 14   |................|
^CINFO:core:Going down...
INFO:openflow.of_01:[00-00-00-00-00-01 1] disconnected
INFO:core:Down.

I can replace it as follows:
`msg.actions.append(of.ofp_action_output(port=0))`
or
`msg.actions.append(of.ofp_action_output(port=of.OFPP_FLOOD))`
and then the error disappears. I can also test it with mininet and confirm that the rule works as expected (i.e. it matches traffic between hosts h1 and h2 and drops it). Pings between h1 and h2 get dropped, but not between h1 and h3 or h2 and h3.

Googling seems to be of no use.

**Comment by MurphyMc** [comment]
This error message is coming from the switch.  The switch seems to not like OFPP_NONE as the output port.  What switch type and version are you using?  I think the used to be an error in old version of Open vSwitch but that newer versions were fine with it.

It's worth noting that this line of code is pretty much useless.  If you don't want to output the packet, rather than creating an output action directed at no port... just don't create an output action.

**Comment by jnfoster** [comment]
One of my students just stumbled on this... 

Assume a controller with this (silly) PacketIn handler:
```
  def _handle_PacketIn(self,event):
    match = of.ofp_match.from_packet(event.parsed)
    msg = of.ofp_flow_mod(match=match)
    msg.data = event.ofp
    msg.actions.append(of.ofp_action_output(port=of.OFPP_NONE))
    event.connection.send(msg)
    return
```
When OVS receives the message, it responds with an error, which is appropriate. 

But, if I'm reading the OVS logs correctly, POX closes the connection:
```
2021-03-16T12:44:54.414Z|02746|ofp_actions|WARN|bad action at offset 0 (OFPBAC_BAD_OUT_PORT):
00000000  00 00 00 08 ff ff 00 00-
2021-03-16T12:44:54.414Z|02747|connmgr|INFO|s1<->tcp:127.0.0.1:6633: sending OFPBAC_BAD_OUT_PORT error reply to OFPT_FLOW_MOD message
2021-03-16T12:44:54.420Z|02748|rconn|INFO|s1<->tcp:127.0.0.1:6633: connection closed by peer
```

This in turn causes POX to report a confusing error message:
```
ERROR:openflow.of_01:Exception reading connection [00-00-00-00-00-01 5]
Traceback (most recent call last):
  File "/home/mininet/pox/pox/openflow/of_01.py", line 940, in read
    h(self, msg)
  File "/home/mininet/pox/pox/openflow/of_01.py", line 206, in handle_ERROR
    msg.show(str(con) + " Error: ").strip())
  File "/home/mininet/pox/pox/openflow/libopenflow_01.py", line 4043, in show
    outstr += prefix + hexdump(self.data).replace("\n", "\n" + prefix)
  File "/home/mininet/pox/pox/lib/util.py", line 485, in hexdump
    data = [ord(c) for c in data]
  File "/home/mininet/pox/pox/lib/util.py", line 485, in <listcomp>
    data = [ord(c) for c in data]
TypeError: ord() expected string of length 1, but int found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mininet/pox/pox/openflow/of_01.py", line 1140, in run
    if con.read() is False:
  File "/home/mininet/pox/pox/openflow/of_01.py", line 944, in read
    ("\n" + str(self) + " ").join(str(msg).split('\n')))
  File "/home/mininet/pox/pox/openflow/libopenflow_01.py", line 612, in __str__
    return self.__class__.__name__ + "\n  " + self.show('  ').strip()
  File "/home/mininet/pox/pox/openflow/libopenflow_01.py", line 4043, in show
    outstr += prefix + hexdump(self.data).replace("\n", "\n" + prefix)
  File "/home/mininet/pox/pox/lib/util.py", line 485, in hexdump
    data = [ord(c) for c in data]
  File "/home/mininet/pox/pox/lib/util.py", line 485, in <listcomp>
    data = [ord(c) for c in data]
TypeError: ord() expected string of length 1, but int found
```

For reference, this is on the version of OVS on the current Mininet VM, which is v2.13.1.

**Comment by MurphyMc** [comment]
Thanks for the bug report; this is a Python 3 thing.  I'm beginning to wish I'd taken a different approach to the str/bytes problems in the Python 3 port, but it's probably too late to bother now.

Should be fixed in my fork here: https://github.com/MurphyMc/pox/commit/8ff3d261d10bcdd3ce42b48409fbe79132c72295

That'll make it into the main repo eventually...

(.. at least partially fixed, anyway.  If you give it a test and it's still weird, please do let me know.)
