### ISSUE TITLE
ERROR:openflow.of_01:Exception reading connection [None 1]

### ISSUE THREAD

**Issue by vieangry** [noxrepo/pox#219]
POX 0.5.0 (eel) / Copyright 2011-2014 James McCauley, et al.
DEBUG:core:POX 0.5.0 (eel) going up...
DEBUG:core:Running on CPython (2.7.12/Nov 12 2018 14:36:49)
DEBUG:core:Platform is Linux-4.15.0-46-generic-x86_64-with-Ubuntu-16.04-xenial
INFO:core:POX 0.5.0 (eel) is up.
DEBUG:openflow.of_01:Listening on 0.0.0.0:6633
ERROR:openflow.of_01:Exception reading connection [None 1]
Traceback (most recent call last):
  File "/home/ubuntu/pox/pox/openflow/of_01.py", line 1132, in run
    if con.read() is False:
  File "/home/ubuntu/pox/pox/openflow/of_01.py", line 926, in read
    new_offset,msg = self.unpackers[ofp_type](self.buf, offset)
  File "/home/ubuntu/pox/pox/openflow/libopenflow_01.py", line 197, in unpack_new
    assert (r-offset) == length, o
AssertionError: ofp_hello
  header: 
    version: 4
    type:    0 (OFPT_HELLO)
    length:  8
    xid:     880
ERROR:openflow.of_01:Exception reading connection [None 2]
Traceback (most recent call last):
  File "/home/ubuntu/pox/pox/openflow/of_01.py", line 1132, in run
    if con.read() is False:
  File "/home/ubuntu/pox/pox/openflow/of_01.py", line 926, in read
    new_offset,msg = self.unpackers[ofp_type](self.buf, offset)
  File "/home/ubuntu/pox/pox/openflow/libopenflow_01.py", line 197, in unpack_new
    assert (r-offset) == length, o
AssertionError: ofp_hello

Does anybody know what went wrong here？

**Comment by MurphyMc** [comment]
See #126 for a workaround.

**Comment by MurphyMc** [comment]
This should be fixed in fangtooth as of murphymc/pox@7030909dd78c138a7eee6d1c61532466847318d3.
