### ISSUE TITLE
unable to use applications like hub through pox controller

### ISSUE THREAD

**Issue by SibasisRath** [noxrepo/pox#277]
Hello murphy I am new to this SDN topic I installed ubuntu 14.04 server distribution in my virtual box and upon that I installed ubuntu desktop. I am trying to use pox controller. I installed it successfully by cloning its source GitHub repository.  I am now inside pox directory where I used a command ./pox.py pox.forwarding.hub to run the SDN hub application but it is showing error   

Traceback (most recent call last):
File "./pox.py", line 43, in
from pox.boot import boot
File "/home/mininet/pox/pox/boot.py", line 41, in
import pox.openflow
File "/home/mininet/pox/pox/openflow/init.py", line 38, in
from. import libopenflow_01 as of
File "/home/mininet/pox/pox/openflow/libopenflow_01.py", line 25, in
from pox.lib.packet.packet_base import packet_base
File "/home/mininet/pox/pox/lib/packet/init.py", line 27, in
from . import arp as ARP
File "/home/mininet/pox/pox/lib/packet/arp.py", line 41, in
from .ipv4 import ipv4
File "/home/mininet/pox/pox/lib/packet/ipv4.py", line 48, in
from .gre import *
File "/home/mininet/pox/pox/lib/packet/gre.py", line 43, in
from . import ipv4
ImportError: cannot import name 'ipv4'

So, I tried to do the exact thing by installing mininet VM and it worked properly.
So, I am not able to understand why it happened in that case and can you suggest any solution for this

**Comment by MurphyMc** [comment]
Before this traceback, is there any POX log?  If so, can you post it?
Also, you said you cloned from github... but which version/branch?

(Also, 14.04 is eight years old!  Is there a reason to use such an old version?)

**Comment by MurphyMc** [comment]
Closed due to lack of followup.
