### ISSUE TITLE
graph.minigraph "object not iterable"

### ISSUE THREAD

**Issue by colin-scott** [noxrepo/pox#36]
Line 47 of lib.graph.minigraph.py is throwing the following exception:

Traceback (most recent call last):
  File "/Users/cs/Research/UCB/sdn-debugger/tests/unit/sts/topology_test.py", line 152, in setUp
    self.g.link((self.switches[0], self.switches[0].ports[2]), (self.switches[1], self.switches[1].ports[2]))
  File "/Users/cs/Research/UCB/sdn-debugger/sts/../pox/pox/lib/graph/graph.py", line 612, in link
    self.disconnect_port(np1)
  File "/Users/cs/Research/UCB/sdn-debugger/sts/../pox/pox/lib/graph/graph.py", line 550, in disconnect_port
    for n1,n2,k,d in self._g.edges(np[0], data=True, keys=True):
  File "/Users/cs/Research/UCB/sdn-debugger/sts/../pox/pox/lib/graph/minigraph.py", line 47, in edges
    nbunch = set(nbunch)
TypeError: 'MockSwitch' object is not iterable

This issue can be reproduced by checkout out the debugger repo (git@github.com:noxrepo/sdn-debugger.git) and running tests.unit.sts.topology_test.py

I'll take a look later -- mostly just documenting this here for later reference.

**Comment by MurphyMc** [comment]
I suggested that this might be a place where minigraph is assuming the nbunch is a sequence of nodes but it was actually passed a single node (which is legal in networkx).

Did you ever look into / resolve this, Colin?
