### ISSUE TITLE
AttributeError: 'Link' object has no attribute 'dpid1'

### ISSUE THREAD

**Issue by colin-scott** [noxrepo/pox#41]
The following exception is thrown:

```
c('127.0.0.1', 8888) [1725] Traceback (most recent call last):
c('127.0.0.1', 8888) [1725]   File "./pox.py", line 420, in <module>
c('127.0.0.1', 8888) [1725]     main()
c('127.0.0.1', 8888) [1725]   File "./pox.py", line 387, in main
c('127.0.0.1', 8888) [1725]     core.scheduler.run()
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/lib/recoco/recoco.py", line 267, in run
c('127.0.0.1', 8888) [1725]     r = self.cycle()
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/lib/recoco/recoco.py", line 293, in cycle
c('127.0.0.1', 8888) [1725]     rv = t.execute()
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/lib/recoco/recoco.py", line 94, in execute
c('127.0.0.1', 8888) [1725]     return self.gen.send(v)
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/openflow/of_01.py", line 760, in run
c('127.0.0.1', 8888) [1725]     if con.read() is False:
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/openflow/of_01.py", line 622, in read
c('127.0.0.1', 8888) [1725]     h(self, msg)
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/openflow/of_01.py", line 151, in handle_PACKET_IN
c('127.0.0.1', 8888) [1725]     con.ofnexus.raiseEvent(PacketIn, con, msg)
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/lib/revent/revent.py", line 280, in raiseEvent
c('127.0.0.1', 8888) [1725]     rv = event._invoke(handler, *args, **kw)
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/lib/revent/revent.py", line 158, in _invoke
c('127.0.0.1', 8888) [1725]     return handler(self, *args, **kw)
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/openflow/discovery.py", line 383, in _handle_PacketIn
c('127.0.0.1', 8888) [1725]     self.raiseEvent(LinkEvent, True, newLink)
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/lib/revent/revent.py", line 280, in raiseEvent
c('127.0.0.1', 8888) [1725]     rv = event._invoke(handler, *args, **kw)
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/lib/revent/revent.py", line 158, in _invoke
c('127.0.0.1', 8888) [1725]     return handler(self, *args, **kw)
c('127.0.0.1', 8888) [1725]   File "/Users/cs/Research/UCB/code/sts/pox/pox/forwarding/l2_multi.py", line 342, in _handle_LinkEvent
c('127.0.0.1', 8888) [1725]     sw1 = switches[l.dpid1]
c('127.0.0.1', 8888) [1725] AttributeError: 'Link' object has no attribute 'dpid1'
```

You can reproduce it by cloning [sts](http://ucb-sts.github.com/sts/) and running:
$ ./simulator.py -c config/pox_attr_error.py

**Comment by MurphyMc** [comment]
This bug only exists in the debugger branch and I don't think I have any plans to merge the problematic code (which is from some of the experimental NOM stuff) into mainline.

Do you want/expect to fix it in the debugger branch, or can this issue be closed?

**Comment by zarifis** [comment]
That's right, this is from when I was trying different object
representations for the NOM. Let me know if you want this solved and I can
take a look
