### ISSUE TITLE
KeyError in discovery.py

### ISSUE THREAD

**Issue by colin-scott** [noxrepo/pox#42]
POX throws the following exception when a socket error errno.EWOULDBLOCK is returned: 

```
Traceback (most recent call last):
  File "/home/rcs/Research/UCB/sts/pox/pox/openflow/of_01.py", line 623, in read
    h(self, msg)
  File "/home/rcs/Research/UCB/sts/pox/pox/openflow/of_01.py", line 135, in handle_FEATURES_REPLY
    con.ofnexus.miss_send_len))
  File "/home/rcs/Research/UCB/sts/pox/pox/openflow/of_01.py", line 591, in send
    self.disconnect()
  File "/home/rcs/Research/UCB/sts/pox/pox/openflow/of_01.py", line 543, in disconnect
    self.ofnexus.raiseEvent(ConnectionDown(self))
  File "/home/rcs/Research/UCB/sts/pox/pox/lib/revent/revent.py", line 280, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/rcs/Research/UCB/sts/pox/pox/lib/revent/revent.py", line 158, in _invoke
    return handler(self, *args, **kw)
  File "/home/rcs/Research/UCB/sts/pox/pox/openflow/discovery.py", line 224, in _handle_ConnectionDown
    self._dps.remove(event.dpid)
KeyError: 1
```

**Comment by MurphyMc** [comment]
This should already be fixed in betta (and _I_ am no longer fixing bugs in older versions).

**Comment by MurphyMc** [comment]
Since I believe this is fixed in betta, I'm closing this.
Please reopen if the problem still exists in betta.
